deploy:
  container:
    manifest: container/base/container-manifest.json
  kustomize:
    path: container/base
run:
  - name: test
    workingDir: container/base
    env:
      - 'ENDPOINT=http://{{ serviceAddress "echo" 5678 }}'
    command: ['go', 'run', 'test.go']