stack:
  family: warp-before
deploy:
  kustomize:
    path: before
setups:
  - name: setup0
    before:
      - waitFor:
          resources: ['onePodPerService']
        name: waitForPods
      - waitFor:
          resources: ['endpoints']
        timeoutSeconds: 600
        name: waitFor
        dependsOn:
          - waitForPods
      - httpGet:
          url: http://{{ serviceAddress "echo" 5678 }}
        timeoutSeconds: 600
        dependsOn:
          - waitFor
        name: waitForEcho
      - run:
          workingDir: before/true
          command: ['go', 'run', 'true.go']
commands:
  - name: test
    setup: setup0
    env:
      - 'ENDPOINT=http://{{ serviceAddress "echo" 5678 }}'
    workingDir: kustomize/base
    command: ['go', 'run', 'test.go']