stack:
  family: warp-kustomize-base
deploy:
  kustomize:
    path: kustomize/base
run:
- name: test
  env:
    - 'ENDPOINT=http://{{ serviceAddress "echo" 5678 }}'
  workingDir: kustomize/base
  command: ['go', 'run', 'test.go']