stack:
  family: warp-env
deploy:
  kustomize:
    path: env
setups:
  - name: setup0
    env:
      - 'ENDPOINT=http://{{ k8sServiceAddress "default" "echo" 5678 }}'
      - 'CONFIG_FOO={{ k8sConfigMapKey "default" "config-map" "foo" }}'
      - 'SECRET_BAR={{ k8sSecretKey "default" "secrets" "bar" }}'
      - 'SERVICE_NAME={{ k8sServiceName "default" "echo" }}'
commands:
  - name: test
    setup: setup0
    workingDir: env
    command: ['go', 'run', 'test.go']